name: Node.js Package
on:
  push:
    branches: [master]
  pull_request:

jobs:
  publish-prod:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: write
    
    steps:
      - uses: actions/checkout@v2

      # Creates tags and updates changelog based on change changelog-config.js settings
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with: 
          github-token: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tfso'
          
      - name: Publish to Github Packages
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
